name: Android CI - Run Specific Test and Upload APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Update Android SDK
      run: |
        yes | sdkmanager --update


    # Step 3: Set up Android SDK and emulator (with proper script)
    - name: Set up Android SDK and start emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        force-avd-creation: true
        script: |
          # Start the emulator in the background
          $HOME/Android/emulator/emulator -avd test -no-window -no-audio -gpu swiftshader_indirect -no-snapshot -accel off &
          # Wait for the emulator to boot up completely
          adb wait-for-device
          # Unlock the screen
          adb shell input keyevent 82
          # Wait a few seconds to make sure everything is ready
          sleep 15

    # Step 4: Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Step 5: Build APK
    - name: Build APK
      run: |
        cd testapp
        ./gradlew clean assembleDebug

    # Step 6: Run Specific Test
    - name: Run Specific Test
      run: |
        cd testapp
        ./gradlew testDebugUnitTest --tests "com.example.myapplication.MainActivityTest"

    # Step 7: Upload APK as artifact
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-apk
        path: testapp/app/build/outputs/apk/debug/app-debug.apk

    # Step 8: Upload test results (optional)
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: testapp/app/build/reports/tests/testDebugUnitTest/
