name: Production Builds
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Release-Build"
        default: "Generate release build"
      testers:
        type: choice
        description: "Select testers"
        options:
          - android
          - internalTesters
          - everyone

permissions:
  contents: write  # Allows write permissions to the repository, needed to create tags and releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checking out branch
        uses: actions/checkout@v3

      # Step 2: Set up Java (Temurin distribution, Java 17)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # Step 3: Set up the Android SDK, which is needed to build Android apps
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10

      # Step 4: Decode the keystore that is stored as base64 in GitHub secrets
      # The decoded keystore is stored in the /testapp path
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > testapp/keystore.jks

      # Step 5: Give executable permissions to the Gradle wrapper
      - name: Give Gradle wrapper execution permissions
        run: chmod +x testapp/gradlew

      # Step 6: Build the release APK using Gradle
      - name: Build Release apk
        run: cd testapp && ./gradlew assembleRelease --stacktrace

      # Step 7: Run Android unit tests on the debug build
      - name: Run Android Tests
        run: cd testapp && ./gradlew :app:testDebugUnitTest --tests "com.example.myapplication.ExampleUnitTest"

      # Step 8: Build the release bundle (AAB file)
      - name: Build Release bundle
        run: cd testapp && ./gradlew bundleRelease --stacktrace

      # Step 9: Create GitHub Release Tag
      - name: Create GitHub Release Tag
        id: create_tag
        run: |
          TAG_NAME="v1.0.${{ github.run_number }}"  # Generate the tag name dynamically
          git tag $TAG_NAME  # Create a tag
          git push origin $TAG_NAME  # Push the tag to the repository
        env:
          TOKEN: ${{ secrets.TOKEN }}

      # Step 10: List files in APK directory (for debugging purposes)
      - name: List files in APK directory
        run: ls -l testapp/app/build/outputs/apk/release/

      # Step 11: List files in AAB directory (for debugging purposes)
      - name: List files in AAB directory
        run: ls -l testapp/app/build/outputs/bundle/release/

      # Step 12: Create Release and Upload Files
      - name: Create Release and Upload Files
        uses: softprops/action-gh-release@v1
        with:
          files: testapp/app/build/outputs/apk/release/app-release-unsigned.apk testapp/app/build/outputs/bundle/release/app-release.aab
        env:
          TOKEN: ${{ secrets.TOKEN }}
